### ISSUE TITLE
Add strings to translate

### ISSUE THREAD

**Issue by exstrim401** [montelibero-org/veche#78]
Add "Close" and "Reopen" buttons as well as "Provide info for" label to translate
Needed for #77

**Comment by cblp** [comment]
This doesn't block #77

**Comment by exstrim401** [comment]
> This doesn't block #77

I want this pull request to be a complete translation

**Comment by cblp** [comment]
> > This doesn't block #77
> 
> I want this pull request to be a complete translation

I'd prefer small independent changes.

**Comment by exstrim401** [comment]
> > > This doesn't block #77
> > 
> > 
> > I want this pull request to be a complete translation
> 
> I'd prefer small independent changes.

I think incomplete translation will be looking worse than none at all

**Comment by exstrim401** [comment]
> Add "Close" and "Reopen" buttons as well as "Provide info for" label to translate
> Needed for #77

"Via Stellar" and "Via Telegram" labels too

**Comment by cblp** [comment]
действительно, нетривиально выходит https://github.com/montelibero-org/veche/commit/9e868d7796c4edc5ded6b5cd8263de47b81766cf

**Comment by cblp** [comment]
"Provide info for" — https://github.com/montelibero-org/veche/commit/bc9621f7bc2dc1e46360490d18fb099415a0a172

**Comment by cblp** [comment]
метки на странице логина готовы https://github.com/montelibero-org/veche/commit/44218c60ae3ffe0839a3c6237f9b24a8324c599b
